export const VIEWER_PRESENCE_COOKIE_NAME = 'viewer_presence'
export const VIEWER_HEARTBEAT_INTERVAL_MS = 60_000
export const VIEWER_PRESENCE_TTL_MS = 3 * VIEWER_HEARTBEAT_INTERVAL_MS
export const VIEWER_PRESENCE_REDIS_CLEANUP_INTERVAL_MS = 60 * 60 * 1000
export const VIEWER_PRESENCE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30
