import { createMcpHandler, experimental_withMcpAuth } from 'mcp-handler'
import { NextRequest } from 'next/server'
import { z } from 'zod'

import {
  SITE_SETTINGS_CORE_CATEGORY_KEYS,
  SITE_SETTINGS_RULES_KEYS,
  SITE_SETTINGS_SCHEDULE_CATEGORY_KEYS,
  SITE_SETTINGS_THEME_CATEGORY_KEYS,
} from '@/constants/site-settings'
import { exportActivityAppsSnapshot } from '@/lib/activity-app-export'
import { enforceApiRateLimit } from '@/lib/api-rate-limit'
import {
  getSafeSiteConfig,
  prepareSiteConfigValuesFromPayload,
} from '@/lib/llm-site-config'
import {
  pickCoreSettingsFromConfig,
  pickRulesSettingsFromConfig,
  pickScheduleSettingsFromConfig,
  pickThemeSettingsFromConfig,
  readEffectiveSiteConfig,
} from '@/lib/site-settings-read'
import { pickRecordKeys } from '@/lib/site-settings-record'
import {
  persistCoreSettingsFromPrepared,
  persistRulesSettingsValues,
  persistScheduleSettingsFromPrepared,
  persistThemeSettingsFromPrepared,
} from '@/lib/site-settings-write'
import { isLegacyMcpEnabled, verifyLegacyMcpApiKey } from '@/lib/skills-auth'

const SITE_SETTINGS_CATEGORY_KEYS = {
  core: SITE_SETTINGS_CORE_CATEGORY_KEYS,
  theme: SITE_SETTINGS_THEME_CATEGORY_KEYS,
  schedule: SITE_SETTINGS_SCHEDULE_CATEGORY_KEYS,
  rules: SITE_SETTINGS_RULES_KEYS,
} as const

type SiteSettingsCategory = keyof typeof SITE_SETTINGS_CATEGORY_KEYS

const UPDATE_SITE_SETTINGS_TOOL_DESCRIPTION = [
  'Update the current Waken site settings through the v2 category storage.',
  'Always choose exactly one `category`: core, theme, schedule, or rules.',
  'Send only the minimal changed fields inside `payload`; never send the full settings object and never mix fields from multiple categories.',
  'Restricted fields must never be written: adminThemeColor, adminBackgroundColor, userNoteTypewriterEnabled, pageLoadingEnabled, searchEngineIndexingEnabled, openApiDocsEnabled, useNoSqlAsCacheRedis, redisCacheTtlSeconds, activityUpdateMode, processStaleSeconds, historyWindowMinutes, steamApiKey, autoAcceptNewDevices, inspirationAllowedDeviceHashes, pageLockEnabled, pageLockPassword, hcaptchaEnabled, hcaptchaSiteKey, hcaptchaSecretKey.',
  'For array/list fields such as appMessageRules, appBlacklist, appWhitelist, appNameOnlyList, mediaPlaySourceRules, mediaPlaySourceBlocklist, schedulePeriodTemplate, scheduleGridByWeekday, and scheduleCourses, send the full final value for that field rather than an incremental append instruction.',
  'For `appMessageRules`, each item should be a grouped object like `{ id?, processMatch, defaultText?, titleRules }`; `id` is an optional string identifier auto-generated by the server if omitted; `processMatch` uses the process name such as `explorer.exe`, and each title rule uses `{ id?, mode: "plain" | "regex", pattern, text }` for matching `processTitle`. Text supports `{process}` and `{title}`; regex title rules also support `{match}`, `{match1}`, `{match2}`, and named captures like `{match:name}`.',
  '`captureReportedAppTitleLimit` controls how many recent window titles are kept per reported app/platform for rule suggestions and app export; values are clamped to 0–10, where 0 keeps app names only.',
  'For `appFilterMode`, only use `blacklist` or `whitelist`; when `appWhitelist` is empty under whitelist mode, no app activity is shown.',
  'For `themePreset`, prefer one of: basic, midnight, forest, sakura, obsidian, ocean, amber, lavender, mono, nord, customSurface. If using `customSurface`, write the theme tokens under `themeCustomSurface`.',
  'Useful `themeCustomSurface` fields include primary, secondary, accent, online, card, border, muted, mutedForeground, homeCardOverlay, homeCardOverlayDark, homeCardInsetHighlight, animatedBgTint1/2/3, floatingOrbColor1/2/3, and animatedBg.',
  'Background image auto-palette / live palette extraction is not only a preview: enabling it may overwrite existing manual color tokens such as background, primary, accent, card, border, muted, and overlay colors. Warn the user before enabling it when a hand-tuned palette already exists.',
  'For `scheduleSlotMinutes`, only use 15, 30, 45, or 60. When editing schedule structure fields, send complete valid JSON values.',
  'For booleans and optional fields, omit the field to keep the existing value.',
  'If a desired display detail is still not exposed via dedicated theme fields, use `customCss` as the fallback global override layer.',
  'If you need to confirm a specific rendered visual effect, visit the live site URL directly and inspect the page instead of inferring appearance only from config values.',
].join(' ')

function pickCategorySettings(
  category: SiteSettingsCategory,
  config: Record<string, unknown>,
): Record<string, unknown> {
  if (category === 'theme') return pickThemeSettingsFromConfig(config)
  if (category === 'schedule') return pickScheduleSettingsFromConfig(config)
  if (category === 'rules') return pickRulesSettingsFromConfig(config)
  return pickCoreSettingsFromConfig(config)
}

function assertCategoryPayload(
  category: SiteSettingsCategory,
  payload: Record<string, unknown>,
): void {
  const allowedKeys = SITE_SETTINGS_CATEGORY_KEYS[category] as readonly string[]
  const invalidKeys = Object.keys(payload).filter((key) => !allowedKeys.includes(key))
  if (invalidKeys.length === 0) return

  const error = new Error(`Fields do not belong to ${category} settings: ${invalidKeys.join(', ')}`)
  ;(error as { status?: number; invalidKeys?: string[] }).status = 400
  ;(error as { status?: number; invalidKeys?: string[] }).invalidKeys = invalidKeys
  throw error
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

function mergeNestedPatchFields(
  payload: Record<string, unknown>,
  currentConfig: Record<string, unknown>,
): Record<string, unknown> {
  const next = { ...payload }
  if (isPlainRecord(payload.themeCustomSurface) && isPlainRecord(currentConfig.themeCustomSurface)) {
    next.themeCustomSurface = {
      ...currentConfig.themeCustomSurface,
      ...payload.themeCustomSurface,
    }
  }
  return next
}

async function readCategorySettings(category: SiteSettingsCategory) {
  const data = await getSafeSiteConfig('admin')
  return data ? pickCategorySettings(category, data as Record<string, unknown>) : null
}

async function updateCategorySettings(
  category: SiteSettingsCategory,
  payload: Record<string, unknown>,
) {
  assertCategoryPayload(category, payload)
  const currentConfig = await readEffectiveSiteConfig()
  if (!currentConfig) {
    const error = new Error('未找到网页配置，请先完成初始化配置')
    ;(error as { status?: number }).status = 400
    throw error
  }

  const mergedPayload = mergeNestedPatchFields(payload, currentConfig)
  const preparedValues = await prepareSiteConfigValuesFromPayload(mergedPayload)
  const pickedValues = {
    ...currentConfig,
    ...pickRecordKeys(preparedValues, SITE_SETTINGS_CATEGORY_KEYS[category]),
  }

  let data: Record<string, unknown> | null
  if (category === 'theme') {
    data = await persistThemeSettingsFromPrepared(pickedValues)
  } else if (category === 'schedule') {
    data = await persistScheduleSettingsFromPrepared(pickedValues)
  } else if (category === 'rules') {
    await persistRulesSettingsValues(pickedValues)
    data = (await getSafeSiteConfig('admin')) as Record<string, unknown> | null
  } else {
    data = await persistCoreSettingsFromPrepared(pickedValues, payload)
  }

  return data ? pickCategorySettings(category, data) : null
}

const mcpHandler = createMcpHandler(
  (server) => {
    server.registerTool(
      'get_site_settings',
      {
        title: 'Get Site Settings',
        description: 'Read one v2 site settings category through the legacy MCP transport.',
        inputSchema: {
          category: z.enum(['core', 'theme', 'schedule', 'rules']),
        },
      },
      async ({ category }) => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await readCategorySettings(category),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )

    server.registerTool(
      'update_site_settings',
      {
        title: 'Update Site Settings',
        description: UPDATE_SITE_SETTINGS_TOOL_DESCRIPTION,
        inputSchema: {
          category: z.enum(['core', 'theme', 'schedule', 'rules']),
          payload: z.record(z.string(), z.unknown()),
        },
      },
      async ({ category, payload }) => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await updateCategorySettings(category, payload),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )

    server.registerTool(
      'export_activity_apps',
      {
        title: 'Export Activity Apps',
        description: 'Export current activity app groups through the legacy MCP fallback.',
        inputSchema: {},
      },
      async () => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await exportActivityAppsSnapshot(),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )
  },
  {
    serverInfo: {
      name: 'waken-wa-legacy-mcp',
      version: '1.0.0',
    },
  },
  {
    basePath: '/api/llm',
    disableSse: true,
  },
)

const authedHandler = experimental_withMcpAuth(
  mcpHandler,
  async (_req, bearerToken) => {
    if (!bearerToken) return undefined
    const enabled = await isLegacyMcpEnabled()
    if (!enabled) return undefined
    const ok = await verifyLegacyMcpApiKey(bearerToken)
    if (!ok) return undefined
    return {
      token: bearerToken,
      clientId: 'legacy-mcp-client',
      scopes: [],
    } as any
  },
  { required: true },
)

const LLM_MCP_TRANSPORT_RATE_LIMIT_MAX = 60
const LLM_MCP_TRANSPORT_RATE_LIMIT_WINDOW_MS = 60_000

async function withRateLimit(request: Request) {
  const nextRequest =
    request instanceof NextRequest ? request : new NextRequest(request.clone())
  const limitedResponse = await enforceApiRateLimit(nextRequest, {
    bucket: 'llm-mcp-transport',
    maxRequests: LLM_MCP_TRANSPORT_RATE_LIMIT_MAX,
    windowMs: LLM_MCP_TRANSPORT_RATE_LIMIT_WINDOW_MS,
  })
  if (limitedResponse) return limitedResponse
  return authedHandler(request)
}

export const GET = withRateLimit
export const POST = withRateLimit
