import { createMcpHandler, experimental_withMcpAuth } from 'mcp-handler'
import { NextRequest } from 'next/server'
import { z } from 'zod'

import { exportActivityAppsSnapshot } from '@/lib/activity-app-export'
import { enforceApiRateLimit } from '@/lib/api-rate-limit'
import { getSafeSiteConfig, updateSiteConfigFromPayload } from '@/lib/llm-site-config'
import { isLegacyMcpEnabled, verifyLegacyMcpApiKey } from '@/lib/skills-auth'

const UPDATE_SITE_SETTINGS_TOOL_DESCRIPTION = [
  'Update the current Waken site settings through the legacy MCP fallback.',
  'Send only the minimal changed fields inside `payload`; never send the full settings object.',
  'Restricted fields must never be written: adminThemeColor, adminBackgroundColor, userNoteTypewriterEnabled, pageLoadingEnabled, searchEngineIndexingEnabled, openApiDocsEnabled, useNoSqlAsCacheRedis, redisCacheTtlSeconds, activityUpdateMode, processStaleSeconds, historyWindowMinutes, steamApiKey, autoAcceptNewDevices, inspirationAllowedDeviceHashes, pageLockEnabled, pageLockPassword, hcaptchaEnabled, hcaptchaSiteKey, hcaptchaSecretKey.',
  'For array/list fields such as appMessageRules, appBlacklist, appWhitelist, appNameOnlyList, mediaPlaySourceRules, mediaPlaySourceBlocklist, schedulePeriodTemplate, scheduleGridByWeekday, and scheduleCourses, send the full final value for that field rather than an incremental append instruction.',
  'For `appMessageRules`, each item should be a grouped object like `{ id?, processMatch, defaultText?, titleRules }`; `id` is an optional string identifier auto-generated by the server if omitted; `processMatch` uses the process name such as `explorer.exe`, and each title rule uses `{ id?, mode: "plain" | "regex", pattern, text }` for matching `processTitle`.',
  'For `appFilterMode`, only use `blacklist` or `whitelist`; when `appWhitelist` is empty under whitelist mode, no app activity is shown.',
  'For `themePreset`, prefer one of: basic, midnight, forest, sakura, obsidian, ocean, amber, lavender, mono, nord, customSurface. If using `customSurface`, write the theme tokens under `themeCustomSurface`.',
  'Useful `themeCustomSurface` fields include primary, secondary, accent, online, card, border, muted, mutedForeground, homeCardOverlay, homeCardOverlayDark, homeCardInsetHighlight, animatedBgTint1/2/3, floatingOrbColor1/2/3, and animatedBg.',
  'For `scheduleSlotMinutes`, only use 15, 30, 45, or 60. When editing schedule structure fields, send complete valid JSON values.',
  'For booleans and optional fields, omit the field to keep the existing value.',
  'If a desired display detail is still not exposed via dedicated theme fields, use `customCss` as the fallback global override layer.',
  'If you need to confirm a specific rendered visual effect, visit the live site URL directly and inspect the page instead of inferring appearance only from config values.',
].join(' ')

const mcpHandler = createMcpHandler(
  (server) => {
    server.registerTool(
      'get_site_settings',
      {
        title: 'Get Site Settings',
        description: 'Read the current Waken site settings through the legacy MCP fallback.',
        inputSchema: {},
      },
      async () => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await getSafeSiteConfig('admin'),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )

    server.registerTool(
      'update_site_settings',
      {
        title: 'Update Site Settings',
        description: UPDATE_SITE_SETTINGS_TOOL_DESCRIPTION,
        inputSchema: {
          payload: z.record(z.string(), z.unknown()),
        },
      },
      async ({ payload }) => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await updateSiteConfigFromPayload(payload),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )

    server.registerTool(
      'export_activity_apps',
      {
        title: 'Export Activity Apps',
        description: 'Export current activity app groups through the legacy MCP fallback.',
        inputSchema: {},
      },
      async () => ({
        content: [
          {
            type: 'text',
            text: JSON.stringify(
              {
                success: true,
                data: await exportActivityAppsSnapshot(),
              },
              null,
              2,
            ),
          },
        ],
      }),
    )
  },
  {
    serverInfo: {
      name: 'waken-wa-legacy-mcp',
      version: '1.0.0',
    },
  },
  {
    basePath: '/api/llm',
    disableSse: true,
  },
)

const authedHandler = experimental_withMcpAuth(
  mcpHandler,
  async (_req, bearerToken) => {
    if (!bearerToken) return undefined
    const enabled = await isLegacyMcpEnabled()
    if (!enabled) return undefined
    const ok = await verifyLegacyMcpApiKey(bearerToken)
    if (!ok) return undefined
    return {
      token: bearerToken,
      clientId: 'legacy-mcp-client',
      scopes: [],
    } as any
  },
  { required: true },
)

const LLM_MCP_TRANSPORT_RATE_LIMIT_MAX = 60
const LLM_MCP_TRANSPORT_RATE_LIMIT_WINDOW_MS = 60_000

async function withRateLimit(request: Request) {
  const nextRequest =
    request instanceof NextRequest ? request : new NextRequest(request.clone())
  const limitedResponse = await enforceApiRateLimit(nextRequest, {
    bucket: 'llm-mcp-transport',
    maxRequests: LLM_MCP_TRANSPORT_RATE_LIMIT_MAX,
    windowMs: LLM_MCP_TRANSPORT_RATE_LIMIT_WINDOW_MS,
  })
  if (limitedResponse) return limitedResponse
  return authedHandler(request)
}

export const GET = withRateLimit
export const POST = withRateLimit
